services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: yarn dev
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: yarn run start
