services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: yarn dev
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: yarn run start
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    profiles:
      - dev
    depends_on: [api]
volumes:
  postgres:
