services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: 123
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - sqlite:/data/sqlite
    command: yarn run dev
volumes:
  sqlite:
