services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: containerexample
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    user: root
    build:
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: yarn dev
  api:
    user: root
    build:
      target: dev
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/api
      - /api/node_modules
    command: yarn dev
volumes:
  pgdata:
