services:
  app:
    build:
      target: prod
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

  api:
    build:
      target: prod
    environment:
      NODE_ENV: production
    command: yarn run start
