services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: yarn run dev
