openapi: 3.0.4

info:
  title: API
  description: API.
  version: 0.1.0

paths:
  /auth/signin:
    post:
      summary: User sign in
      description: Authenticates user and returns access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
      responses:
        "200":
          description: Sign in successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /auth/signout:
    post:
      summary: User sign out
      description: Invalidate access token.
      security:
        - bearerAuth: []
      responses:
        "501":
          $ref: "#/components/responses/NotImplemented"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Forbidden:
      description: No authorization to perform action
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotImplemented:
      description: Endpoint not implemented yet
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    AuthToken:
      type: object
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    Error:
      type: object
      properties:
        code:
          type: string
          example: RESOURCE_NOT_FOUND
        message:
          type: string
          example: The requested resource could not be found.
        details:
          type: string
          example: Resource(s) does not exist
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
          example: bobhasd@containerexample.com
